language: python
python:
    - 3.4
    - 2.7
    - 2.6
    - 3.3
    - pypy
    - 3.5-dev
    - nightly
sudo: false
install:
    - pip install --upgrade pytest .
script:
    # assert=plain workaround for pytest#774
    - py.test --assert=plain test_pampylho.py

